name: MagnetPlugin
version: ${version}
description: ${description}
main: ru.garde.magnet.MagnetPlugin
api-version: '1.16'
authors: [Garde1]

commands:
  magnet:
    description: Gives magnet items and manages magnetic cores
    usage: /magnet
    aliases: [magnit]
    permission: magnet.use

permissions:
  magnet.use:
    description: Allows use of the Magnet command and all current subcommands
    default: true
