name: MagnetPlugin
version: ${version}

main: ru.garde.magnet.MagnetPlugin
bootstrapper: ru.garde.magnet.MagnetPluginBootsTrap
api-version: '1.21'
author: Garde1

commands:
  magnet:
    description: Gives magnet item and manages magnetic cores
    usage: /magnet
    aliases: [magnit]
